### ISSUE TITLE
MediaList and infinite filtering

### ISSUE THREAD

**Issue by lethargilistic** [lethargilistic/PyMoe#1]
So, I'm implementing an `Abstractions` class called `MediaList`. Basically, it's a list subclass that allows you to write something like this:

```Python
instance = Mal('lethargilistic', 'PASSWORD')
userlist = instance.user('lethargilistic').anime.list
#userlist is a MediaList, which is a list with extra methods like...
shows_not_yet_released = userlist.planned
#shows_not_yet_released is a regular list with the relevant shows
```

The MediaList has a hashmap inside that has an entry for each anime/manga, and lists of hashes that correspond to shows with different statuses. These are generated on creation of the MediaList so that only one pass through the entire list is necessary for getting all the categorical information. When a method like `planned` is called, the `MediaList` refers to its list of planned hashes and returns the corresponding information from its hashmap.

And I'm thinking "Why stop there?" Maybe we could write something like this:

```Python
shows_from_filter = userlist.completed.rated(10).publisher('Sunrise').year('2014')
```

But this won't work unless each of those methods returns a new MediaList, which requires a pass through the whole list for the categorization to work. The slowdown may be significant as more filters are used.

Does this seem like a worthwhile direction to explore?

**Comment by Mahi** [comment]
I personally believe you should use properties/attributes of the show instances rather than methods like `rated()` and `publisher`, and just use the "lame" way of list comprehension:

```
shows_from_filter = [
    show for show in userlist
    if show.completed
    and show.rating == 10
    and show.publisher == 'Sunrise'
    and show.year = 2014
]
```

Or you can use `filter` too:

```
shows_from_filter = filter(
    lambda show: show.completed and show.rating == 10,
    userlist
)
```

Neither of theses is as "fancy" and beautiful as your solution, but they both loop through the iterable only once, resulting into O(n) speed instead of your suggested O(n^2)

**Edit:** If you come up with a way to implement your method and still end up with O(n), then it's neat although still a bit niche. SQLAlchemy solved this by not actually doing anything until a final `.all()` method is called, i.e. you can do:

```
query = session.query(User, Weapon)
query = query.filter(User.type == 'warrior', Weapon.durability >= 15)
# You can always combine those lines ^
```

This constructs a single query, which basically adds all these conditions and filters to a list, and finally when you do:

```
results = query.all()
```

It will all be executed in one loop, comparing each element to all of the filters added.

I'm not sure this is worth the job though....

**Comment by lethargilistic** [comment]
Thanks for the feedback! Disregard the ratings, publisher, etc. concern for now.

Firstly, the filtering by tag method I used reduces to SAT, so, if I could get it down to O(n), I'd be collecting on a million dollars and an automatic PhD for proving P=NP. xD The computer scientist in my heart is all about reducing time complexity, but I think this is a case where practical concerns should win out. 

Most use of this library will be retrieving the user's list of Anime or Manga and filtering to see what the status of each type is. We should make the common case fast. 

Here are some sample big users in terms of anime:
- [Digibro](https://myanimelist.net/profile/Digibro) has 1,827.
- [spacecowboy](https://myanimelist.net/profile/spacecowboy) (NSFW) has 12,210. (presumably the largest and I don't believe it for a femptosecond)

Most MAL pages are skewed towards `UserStatus.Complete` like spacecowboy, because most internet anime fans seem to be masochists. Digibro has a more balanced distribution of each category. In either case, filtering over the entire list with a list comprehension or `filter` just to find all the `UserStatus.Onhold` spends a _lot_ of time failing conditional tests. `MediaList.__init__` does all that processing without any conditionals, and exposes the result as a property that is not evaluated fully until the first time it's used. 

The cost of this approach is an increase in setup time, but by how much?

![this much](http://imgur.com/FoURPHO.png)

The version with `MediaList` ran faster in this sample, but I think that's probably just due to different conditions within my computer because `MediaList` does strictly more setup than a standard `list`. All of my samples ran like this, but my takeaway is that the setup time of the two versions is at least _comparable_, even in the largest practical cases.

And, for whatever cost there is, what speedup do we get? This is filtering for `UserStatus.Completed` anime, the worst case for both:

![still fast](http://imgur.com/eWfigWl.png)

It's 3x faster for the largest user.

And that's the worst case. The best cases for spacecowboy is `UserStatus.Onhold` or `UserStatus.Dropped` because they're empty or extremely sparse. With filtering, it takes the same amount of time as the worst case. With the hashing, sparse cases are virtually instantaneous, even as the total size of the list increases.

And then there's the benefits in program readability:

``` Python
completed = [show for show in userlist if x.status.series == UserStatus.Completed]
```

The variable `completed` can be replaced with:

``` Python
userlist.completed
```

After the first call (faster than the list comprehension), the `completed` property has been evaluated, so you get the _same_ performance as using the variable completed. Yet you don't need to have a list comprehension in your code, so it just reads as what it is.

So that's why I think the O(n^2) hashing is better than the O(n) list comprehension in this common case scenario.

Adding the other filters into the mix, ignoring the cascading issue for one more moment, can then still look like this because the property is a list itself:

``` Python
the_best = [
    show for show in userlist.completed
    if show.user.rating == '10' #really should be an integer
    and show.episodes.total == '26' #same here
]
```

And, also, because `MediaList` is a subclass of `list`, you can still do stuff like this:

``` Python
all_the_worst = [show for show in userlist if show.user.rating == '1']
```

**Comment by lethargilistic** [comment]
I've been thinking about this for a while, and I think you're right that SQLAlchemy's method would be 1) the sensible way to do this, and 2) wouldn't be worth implementing. It'd be a clunky distraction, rather than a beneficial feature.

Instead, I'm going to explore adding category lists for different things. Ratings and series type come to mind. If I go too far and everything slows to a huge, memory hogging crawl...then I think here is a good place to come back to. x3

**Comment by lethargilistic** [comment]
This was a good exercise, but it did end up being a lot slower. xD
